name: Pipeline
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run code
      run:
        python hello.py
  build:
    needs: [test]
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
